### ISSUE TITLE
`1.0.91` update breaks `cargo-xwin`

### ISSUE THREAD

**Issue by namse** [rust-lang/cc-rs#1026]
related issue: https://github.com/rust-cross/cargo-xwin/issues/104

minimal reproducible example: https://github.com/namse/cc-rs-1.0.91-issue

Would you please check this problem?

**Comment by NobodyXu** [comment]
I think this is related to #1015 cc @russelltg

**Comment by NobodyXu** [comment]
@namse I've opened #1027 , can you please try it out?

**Comment by namse** [comment]
@NobodyXu Works very well I guess?
![image](https://github.com/rust-lang/cc-rs/assets/3580430/42ed5821-529e-451d-8598-4e784c1095cf)

**Comment by namse** [comment]
1.0.91 fails build on mimalloc crate
![image](https://github.com/rust-lang/cc-rs/assets/3580430/6d1b89e4-cced-4b61-b8ae-44af1fbde7fe)

but on `cc = { git = "https://github.com/rust-lang/cc-rs.git", rev = "a03257af4a578cd2b7842b6109a6d817035d7a38" }`, it build well (previous screenshot https://github.com/rust-lang/cc-rs/issues/1026#issuecomment-2042724521)

**Comment by namse** [comment]
Would you make a 1.0.92 tag to release to crate.io?

**Comment by NobodyXu** [comment]
Thanks, I've published the release
