### ISSUE TITLE
Support compiling to wasm targets

### ISSUE THREAD

**Issue by jozanza** [rust-lang/cc-rs#1069]
PR: https://github.com/rust-lang/cc-rs/pull/1068

For more context, in a wasm game engine SDK I maintain ([`turbo`](https://crates.io/crates/turbo-genesis-sdk)), I'm pulling in a crate ([`solana-sdk`](https://crates.io/crates/solana-sdk)). However, `cc-rs` is deeply buried in dependencies of dependencies of that crate. This wouldn't be a terrible problem since `cc-rs` (especially the parallel feature stuff) is far from any code path that runs in wasm and optimization can get rid of a unused code, however, the `compile_error!` macro prevents `cc-rs` prevents builds from ever completing in the first place.

So the only option in my case (where `cc-rs` is buried deep in the dependency tree and I'm targeting wasm) currently is to fork and patch. This gets brittle fairly quickly since other dependencies can have version conflicts and force me to create more branches with version bumps and other minor tweaks over time.

I'm hoping we can land this patch and carve out exceptions for wasm with `compile_error!` moving forward 🙏🏽

**Comment by madsmtm** [comment]
This was fixed by https://github.com/rust-lang/cc-rs/pull/1160, and can be closed.
