### ISSUE TITLE
[Feature Request] Remove `-ccbin` flag on demand

### ISSUE THREAD

**Issue by QuarticCat** [rust-lang/cc-rs#1084]
On Arch Linux, without the `-ccbin` flag, `nvcc` will choose `g++-13` by default. However, `cc` generates `-ccbin=c++` which links to GCC 14, causing compile errors. Although on my own machine, I can specify the `CXX` environment variable, I can't simply fix the version for lib users. The best way to fix this problem is to remove the `-ccbin` flag and let `nvcc` decide host compiler by itself.

**Comment by NobodyXu** [comment]
Having a new function for this does sound reasonable.
