### ISSUE TITLE
>= 1.0.102 wasm build breaks

### ISSUE THREAD

**Issue by juntyr** [rust-lang/cc-rs#1125]
https://github.com/rust-lang/cc-rs/pull/1114 conflates wasm with wasi targets. While wasi targets should change the sysroot to the wasi-sdk-provided one, the non-wasi target `wasm32-unknown-unknown` should probably keep the default sysroot.

https://github.com/rust-lang/cc-rs/pull/1105 extended the disabling of wasm exceptions from just `wasm32-wasip1` to all wasi wasm targets. While this is technically correct, I am building a `wasip1` module *with* exceptions (by stubbing some functions), which broke after upgrading cc. Perhaps cc could somehow allow a build-script to opt out of disabling the exceptions?

Thank you for your help!

**Comment by NobodyXu** [comment]
> the non-wasi target wasm32-unknown-unknown should probably keep the default sysroot.

Thanks, so looks like we need to special case it.

> While this is technically correct, I am building a wasip1 module with exceptions (by stubbing some functions), which broke after upgrading cc.

Maybe `CRATE_CC_NO_DEFAULTS` could help here?

**Comment by juntyr** [comment]
> > While this is technically correct, I am building a wasip1 module with exceptions (by stubbing some functions), which broke after upgrading cc.
> 
> Maybe `CRATE_CC_NO_DEFAULTS` could help here?

Thanks for the suggestion! Setting `CRATE_CC_NO_DEFAULTS=1` did get me closer to a solution, though I had to manually set some flags, e.g. `-O3`, myself to regain the previous behavior. This is good enough for me right now :)
