### ISSUE TITLE
Cyclic package dependency with certain package features set

### ISSUE THREAD

**Issue by ldm0** [rust-lang/cc-rs#1146]
Create a simple cargo project with these dependencies in Cargo.toml

```
parking_lot = { version = "0.12.3", features = ["deadlock_detection"] }
once_cell = { version = "1.19.0", features = ["parking_lot"] }
cc = { version = "1.1.0", features = ["parallel"] }
```

Run `cargo check`, then cargo will emits error:
```
error: cyclic package dependency: package `backtrace v0.3.73` depends on itself. Cycle:
package `backtrace v0.3.73`
    ... which satisfies dependency `backtrace = "^0.3.60"` of package `parking_lot_core v0.9.10`
    ... which satisfies dependency `parking_lot_core = "^0.9.3"` of package `once_cell v1.19.0`
    ... which satisfies dependency `once_cell = "^1.19"` of package `cc v1.1.0`
    ... which satisfies dependency `cc = "^1.0.97"` of package `backtrace v0.3.73`
```

The dependencies formed a cycle after https://github.com/rust-lang/cc-rs/pull/1037 (which introduces the `once_cell` dependency)

**Comment by NobodyXu** [comment]
`once_cell` is used if feature `cc/parallel` is enabled, so if that feature is disabled it should be ok.

We use `once_cell` since `parallel` feature needs `get_or_try_init`:

https://github.com/rust-lang/cc-rs/blob/bd5a4ec0e1faf12d41536e5ca3ec3678fedd47a2/src/parallel/job_token.rs#L189

The one in std `OnceLock` is still unstable rust-lang/rust#109737 , and our MSRV is too low with objection to increase it  #1144

**Comment by ldm0** [comment]
Yeah, I understand that `OnceCell` is somehow necessary there, and MSRV bumping is [not that easy](https://github.com/rust-lang/cc-rs/issues/1144) :-(.

I haven't enabled `cc/parallel` by myself, one node on the project dependency graph does: <https://github.com/gyscos/zstd-rs/blob/main/zstd-safe/zstd-sys/Cargo.toml#L63>. Therefore, I can't disable the feature flag without forking `zstd-sys`, and I suspect there will be more dependencies enabling `cc/parallel` in the future. As long as one crate on the dependency graph does this, the whole project will be affected.

I've already patched `cc-rs`(by replacing `OnceCell` with `OnceLock`) to workaround this problem locally.

**Comment by NobodyXu** [comment]
> I've already patched cc-rs(by replacing OnceCell with OnceLock) to workaround this problem locally.

It would be awesome if you can open a PR with the patch!

**Comment by ldm0** [comment]
> > I've already patched cc-rs(by replacing OnceCell with OnceLock) to workaround this problem locally.
> 
> It would be awesome if you can open a PR with the patch!
> 
> I will do the code review

Yeah I am happy to open a PR.

However, the main problem is that `OnceLock` was stablized in [`1.70`](https://doc.rust-lang.org/nightly/src/std/sync/once_lock.rs.html#102), while MSRV of `cc` is `1.67`.

Using `OnceLock`  is suitable for us but it breaks MSRV, so I suspect it's not for everyone. :-/

**Comment by NobodyXu** [comment]
> However, the main problem is that OnceLock was stablized in 1.70, while MSRV of cc is 1.67.

I would accept a PR, this msrv bump is necessary to fix the compilation error.

**Comment by NobodyXu** [comment]
Alternative solution if we don't want to bump MSRV, is to vendor the `once_cell::sync`
