### ISSUE TITLE
From 1.0.106 rustc_codegen_cranelift's users are blocked!

### ISSUE THREAD

**Issue by frederikhors** [rust-lang/cc-rs#1156]
From [cc-v1.0.106](https://github.com/rust-lang/cc-rs/releases/tag/cc-v1.0.106) we, users of the amazing https://github.com/rust-lang/rustc_codegen_cranelift, cannot build anymore (at least on Windows): https://github.com/rust-lang/rustc_codegen_cranelift/issues/1510.

Can we found an alternative way?

**Comment by NobodyXu** [comment]
Hmmm... in that case, maybe we can revert that changes (and the msrv)?

**Comment by frederikhors** [comment]
Yeah, thanks. Anyway I can alert you here when the fix will be there.

**Comment by NobodyXu** [comment]
Reverted in #1157 would cut a new release shortly

**Comment by frederikhors** [comment]
Thank you very much!
