### ISSUE TITLE
Add objects option

### ISSUE THREAD

**Issue by theaddonn** [rust-lang/cc-rs#1165]
we already have the `.object` function which allows us to include a single extra object, but if we for example use nasm to generate objects from our asm we get a vector full of paths... here would a `.objects` function that takes in multiple objects be very helpful!

**Comment by NobodyXu** [comment]
That sounds like a good addition to the API!

I would welcome any contribution for this feature.

**Comment by Adrian8115** [comment]
I am rn working on a pr, should be finished in a few minutes

**Comment by Adrian8115** [comment]
pr here we go: https://github.com/rust-lang/cc-rs/pull/1166
hope it's all good :3

**Comment by NobodyXu** [comment]
Thanks, I've merged it

**Comment by madsmtm** [comment]
This has been fixed by https://github.com/rust-lang/cc-rs/pull/1166, and can be closed

**Comment by theaddonn** [comment]
oh shoot, sorry forgot to close the issue
