### ISSUE TITLE
Issue/Docs: Dead links and domain hijacking?

### ISSUE THREAD

**Issue by tadghh** [rust-lang/cc-rs#1172]
The "Compile-time Requirements" section contains a few dead links. The Win-builds link now goes to someones blog "if im wrong my bad!" when I think it should lead to here https://github.com/alex85k/winbuilds/blob/master/README.md

Another issue is the "here" link for MSYS2, the section/header it refers to no longer exists `https://github.com/rust-lang/rust#building-on-windows`.
The following looks like a good replacement.
https://github.com/rust-lang/rust/blob/master/INSTALL.md#building-on-windows

**Comment by tadghh** [comment]
https://docs.rs/cc/latest/cc/index.html#compile-time-requirements

**Comment by NobodyXu** [comment]
Thank you, I'll open a PR immediately for this

**Comment by tadghh** [comment]
> Thank you, I'll open a PR immediately for this

You removed the new win-builds link from your first commit. Was this on pourpose?
