### ISSUE TITLE
`emcc`/`em++` are detected as `ToolFamily::Msvc`

### ISSUE THREAD

**Issue by meowtec** [rust-lang/cc-rs#1185]
introduced by: https://github.com/rust-lang/cc-rs/pull/1015
https://github.com/rust-lang/cc-rs/blob/main/src/tool.rs#L173-L174 

For Msvc family, it will add `-nologo` as default flags., but emcc or em++ does not accept this.

**Comment by NobodyXu** [comment]
Thanks.

Does it define any macro that we could use to identify it?

We have a c source file for it, if there's a macro then we could use it.

https://github.com/rust-lang/cc-rs/blob/main/src/detect_compiler_family.c

**Comment by meowtec** [comment]
> Thanks.
> 
> Does it define any macro that we could use to identify it?
> 
> We have a c source file for it, if there's a macro then we could use it.
> 
> https://github.com/rust-lang/cc-rs/blob/main/src/detect_compiler_family.c

Yes, it is `__EMSCRIPTEN__`.

I modified  `detect_compiler_family.c` to this:

```diff
#ifdef __clang__
#pragma message "clang"
#endif

#ifdef __GNUC__
#pragma message "gcc"
#endif

+ #ifdef __EMSCRIPTEN__
+ #pragma message "emscripten"
+ #endif
```

And the `stdout` is:

```
# 1 "/path/todetect_compiler_family.c"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 413 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "path/to/detect_compiler_family.c" 2

#pragma message("clang")



#pragma message("gcc")



#pragma message("emscripten")

```

Hope this will help.
