### ISSUE TITLE
VxWorks wr-cc is detected as MSVC compiler, cc adds flags "no-logo", "W4" and "--" which causes compilation issues.

### ISSUE THREAD

**Issue by biabbas** [rust-lang/cc-rs#1197]
More discussion at Zulip: https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/Optimizing.20Compiler.20builtins.20causes.20build.20failure.20on.20VxWorks

Follow up of issue: https://github.com/rust-lang/compiler-builtins/issues/679

**Comment by NobodyXu** [comment]
Does VxWorks wr-cc define any macro?

If it does, then we could use it to detect VxWorks wr-cc compiler.

**Comment by biabbas** [comment]
> Does VxWorks wr-cc define any macro?
> 
> If it does, then we could use it to detect VxWorks wr-cc compiler.

Yes. It does have __VXWORKS__ macro. I'll try using this. Additional to this whenever compiling a program, cc-crate would add `target=somevxworkstarget`. For VxWorks this behavior causes issues as each wr-cc is configured for one target.

**Comment by biabbas** [comment]
How does it distinguish clang from msvc on linux. On linux _GNUC_ and _clang_ both would be defined.

**Comment by NobodyXu** [comment]
You could put it in detect_compiler_family.c then modify compiler.rs to support VxWorks wr-cc

**Comment by NobodyXu** [comment]
> How does it distinguish clang from msvc on linux. On linux _GNUC_ and _clang_ both would be defined.

We pass `-?` to the compiler to detect msvc.

**Comment by biabbas** [comment]
Oh

> > How does it distinguish clang from msvc on linux. On linux _GNUC_ and _clang_ both would be defined.
> 
> We pass `-?` to the compiler to detect msvc.

Yeah. For some reason `wr-cc -?` returns 0.
