### ISSUE TITLE
Support for wasm32-wasip1-threads

### ISSUE THREAD

**Issue by oligamiq** [rust-lang/cc-rs#1217]
The -pthread is required as a flag.
For -D_WASI_EMULATED_MMAN, it is not necessary yet because the Rust compiler does not support it!

**Comment by NobodyXu** [comment]
Sorry I didn't quite get you.

cc-rs only compiles the source code and produce an archive, it does not performing linking, so I don't think `-pthread` is needed

**Comment by oligamiq** [comment]
When compiling C or C++ for wasm32-wasip1-threads, it is necessary to include the -pthreads flag. Otherwise, during linking, you will encounter an error such as:

note: wasm-ld: error: --shared-memory is disallowed by dlmalloc.o because it was not compiled with 'atomics' or 'bulk-memory' features.

**Comment by NobodyXu** [comment]
> When compiling C or C++ for wasm32-wasip1-threads, it is necessary to include the -pthreads flag. Otherwise, during linking, you will encounter an error such as:

cc-rs **does not perform linking**, it merely compiles them.

**Comment by NobodyXu** [comment]
> When compiling C or C++ for wasm32-wasip1-threads, it is necessary to include the -pthreads flag. Otherwise, during linking, you will encounter an error such as:
> 
> note: wasm-ld: error: --shared-memory is disallowed by dlmalloc.o because it was not compiled with 'atomics' or 'bulk-memory' features.

So `-pthread` needs to be provided when compiling objects, otherwise the linking will fail?

Hmmm I didn't know that `-pthread` flag has that effect during compilation.

**Comment by oligamiq** [comment]
Yes

**Comment by NobodyXu** [comment]
In that case, we might want to special case for this target

**Comment by oligamiq** [comment]
Small example:
https://github.com/oligamiq/small_example_pthread

Running the command `cargo +nightly b --target wasm32-wasip1-threads` fails.

However, when I replace `rusqlite` in `Cargo.toml`, it succeeds.  
The only patch applied is for pthreads:  
https://github.com/oligamiq/rusqlite/commit/95bcbdf080f6385ab6bd5dbf596b97cc58b8bbb5

**Comment by NobodyXu** [comment]
Thanks, I can reproduce this.

Will create a PR for it.
