### ISSUE TITLE
C code is not getting optimized in nightly

### ISSUE THREAD

**Issue by SakiiCode** [rust-lang/cc-rs#1227]
### Code

I am using the cc crate and a build.rs script to compile C code in my [fisher](https://github.com/SakiiCode/fisher) project and observing increased run times in nightly. The running time is similar to opt-level=0 or slightly longer even.

```
$ rustup override set nightly-2024-07-30
$ cargo test --release --package fisher --lib -- proc5x5_large --exact --show-output --include-ignored
...
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 31 filtered out; finished in 37.43s
$ rustup override set nightly-2024-07-29
$ cargo test --release --package fisher --lib -- proc5x5_large --exact --show-output --include-ignored
...
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 31 filtered out; finished in 21.19s
```

### Version it worked on

```
rustc 1.82.0-nightly (2cbbe8b8b 2024-07-28)
binary: rustc
commit-hash: 2cbbe8b8bb2be672b14cf741a2f0ec24a49f3f0b
commit-date: 2024-07-28
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 18.1.7`
```

### Version with regression

```
rustc 1.82.0-nightly (612a33f20 2024-07-29)
binary: rustc
commit-hash: 612a33f20b9b2c27380edbc4b26a01433ed114bc
commit-date: 2024-07-29
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 18.1.7
```

**Comment by madsmtm** [comment]
It is interesting though that it regresses between versions of `rustc`, that's quite odd!

**Comment by madsmtm** [comment]
Could you find the compiler command that `cc` invokes? I think it may be shown with `-v` or `-vv`, otherwise you'll have to dig it out of `target/debug/build/cc-*/output`

**Comment by workingjubilee** [comment]
Yes. It is possible I have misunderstood exactly what @SakiiCode is reporting, however, so please let me know if I should move this back. It is possible there is a commit in this range https://github.com/rust-lang/rust/compare/2cbbe8b8bb2be672b14cf741a2f0ec24a49f3f0b...612a33f20b9b2c27380edbc4b26a01433ed114bc that does in fact clearly explain why rustc is the problem here. https://rust-lang.github.io/cargo-bisect-rustc/ can be used to find it.

**Comment by SakiiCode** [comment]
Found the build commands, it is identical in both cases
```
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-Wall" "-Wextra" "-ffast-math" "-o" "/home/*******/target/release/build/fisher-35f8c4bda9aedc53/out/2e40c9e35e9506f4-asa643.o" "-c" "src/asa643.c"
```
and the output files `2e40c9e35e9506f4-asa643.o` and `libfexact.a` are also identical.

However, the final output is consistently ~ 2kB larger in the bad version. Tried both the original project (dylib) and just the necessary parts (executable). The rust functions don't have slowdowns.

**Comment by SakiiCode** [comment]
cargo-bisect-rustc points to this commit: https://github.com/rust-lang/rust/commit/80d8270d8488957f62fbf0df7a19dfe596be92ac

**Comment by madsmtm** [comment]
That's... [this range of `compiler_builtins`](https://github.com/rust-lang/compiler-builtins/compare/0.1.109...compiler_builtins-v0.1.114) changes.

Perhaps you could change downgrade `compiler_builtings` on the latest `nightly`, and see if it still reproduces? Either by rebuilding `std`, or by using `-Zbuild-std` with cargo patches. And if so, try to bisect the compiler_builtins versions, though I know that's a bit troublesome.

**Comment by SakiiCode** [comment]
I can't manage to get either of that working, unfortunately my skills end here. Can you give more detailed instructions or try in [this minimal repo](https://github.com/SakiiCode/fisher-regression)?

**Comment by SakiiCode** [comment]
Looks like this problem was already fixed around Aug 29
I assumed `rustup override set nightly` is enough to get the latest but now it makes more sense
Thanks for the help!
