### ISSUE TITLE
Add a way to get detault tools that `cc` will use (CC, AR, LD, etc)

### ISSUE THREAD

**Issue by tgross35** [rust-lang/cc-rs#1233]
`cc` uses a handful of environment variables to figure out which tools to use such as `CC`, `AR`, and the suffixed versions of these. Would it be possible to expose this logic somehow? Something along the lines of:

```rust
pub mod tools {
    pub fn ar() -> Option<PathBuf>;
    pub fn cc() -> Option<PathBuf>;
    pub fn ld() -> Option<PathBuf>;
}
```

These would expose the default compiler, archiver, and linker that `cc` would use for the target if not overridden. And then `Build` would call these to actually do its job.

This would be helpful when wanting to build some things with `cc` and need to do some things manually, but need to make sure the same tools are used for consistency.

**Comment by NobodyXu** [comment]
We have
 - [`Build::get_ranlib`](https://docs.rs/cc/latest/cc/struct.Build.html#method.get_ranlib)
 - [`Build::get_archiver`](https://docs.rs/cc/latest/cc/struct.Build.html#method.get_archiver)
 - [`Build::get_compiler`](https://docs.rs/cc/latest/cc/struct.Build.html#method.get_compiler)

cc does not perform any linking so no linker is used.

**Comment by tgross35** [comment]
I don’t know how I never noticed that. Thanks!
