### ISSUE TITLE
Mechanism for automatically passing flags used by rustc

### ISSUE THREAD

**Issue by mrkajetanp** [rust-lang/cc-rs#1254]
When cc-rs is running in a build script, it currently does not check which flags were passed to rustc.

There are some flags which in order to be fully effective need to be passed to both rustc and cc, a good example being AArch64 branch protection - if the Rust code is built with BTI but the C component is not, that will disable BTI for the whole binary.

Would some mechanism for checking which flags were passed to rustc and determining their corresponding cc flags be desirable to have? This could either be in the form of adding them in automatically, a separate function such as `inherit_rustc_flags()` or even just a warning to the user that some flags that should match don't match.

I'm thinking about implementing something along the lines of what I described above, but I wanted to ask for some thoughts from people who work on this crate. Is this desirable in the first place? If so, roughly what direction should I go in with this?

**Comment by NobodyXu** [comment]
Thanks, we definitely want more data to be fetcher from cargoz

Can you provide more details on what rustc/cargo flags it is?

**Comment by mrkajetanp** [comment]
The specific case I'm coming at this with is `-Z branch-protection`, e.g. `-Z branch-protection=pac-ret,bti`.
The corresponding cc flag would be `-mbranch-protection=pac-ret+bti`.
I imagine this would apply to some other flags too and in the end we could just have a `rustc => cc` flag match statement that could be expanded over time.
We can read the flags through `CARGO_ENCODED_RUSTFLAGS` and parse those from there.

**Comment by NobodyXu** [comment]
Thanks that's a good idea, I would accept a PR for it.

**Comment by mrkajetanp** [comment]
Sounds good, will write up a PR then.
Should this be an opt-in thing with its own builder function? E.g. like
```
cc::Build::new().file("foo.c").inherit_rustc_flags().compile("foo");
```
Or should we have this done by default with some opt-out?

**Comment by NobodyXu** [comment]
I think opt-out makes more sense, or maybe we don't even need an opt-out mechanism.

AFAIK the current cargo env usage does not have any opt-out mechanism.
