### ISSUE TITLE
Object file hash prefix creates determinism issues

### ISSUE THREAD

**Issue by nmattia** [rust-lang/cc-rs#1271]
Hi,

I've noticed that when generating object files, the full path of the source files [is hashed](https://github.com/rust-lang/cc-rs/blob/7dd2c0a4afbf066ccf1001eda2efc9d9c17ecf32/src/command_helpers.rs#L311-L312) and included in the object file name. This causes some issues in build systems like Bazel and Nix because the intermediary files will change depending on the directory where the build is performed. This also seems to influence the final output.

I've created a strawman [PR](https://github.com/rust-lang/cc-rs/pull/1270) with a fix that I've only tested on 1.0.83, though it makes some assumptions about where the source files are located.

What would be a good way of fixing this?

Thanks!

**Comment by NobodyXu** [comment]
You can use `compile_intermediates`, which output paths to the objects compiled and you can assmble it manually from there.

**Comment by nmattia** [comment]
Fixed in #1270
