### ISSUE TITLE
Regression >= 1.1.32 unable to build on buildsystems which set tune buildflags, e.g. yocto

### ISSUE THREAD

**Issue by mlilien** [rust-lang/cc-rs#1296]
With version 1.1.32 a build system which already sets tune buildflags can't build anymore.
E.g. for a raspberry pi 3 in yocto, i get
```
|   cargo:warning=arm-omnect-linux-gnueabi-gcc: error: -mfloat-abi=soft and -mfloat-abi=hard may not be used together
 ```
I would prefer a feature or an option via envvar to prevent cc from guessing compile flags.

**Comment by madsmtm** [comment]
That sounds like a custom target, which is very difficult for `cc` to support.

What is the expected value for `-mfloat-abi`?

**Comment by mlilien** [comment]
Yes, it is a custom target which sets `-mfloat-abi=hard`. It clashes with https://github.com/rust-lang/cc-rs/blob/main/src/lib.rs#L2222-L2231. 
a way to prevent `cc` from setting additional flags, e.g. via env var would be nice. in my project `cc` is used by a dependency.

**Comment by mlilien** [comment]
`CRATE_CC_NO_DEFAULTS` works! Thank you!
