### ISSUE TITLE
`build: Inherit flags from rustc` causes rustc build failures

### ISSUE THREAD

**Issue by clubby789** [rust-lang/cc-rs#1321]
https://github.com/rust-lang/rust/pull/134425#issuecomment-2549090540

Bisected to #1279

Looks like we get something like
```
/usr/bin/ld: /rustroot/bin/../lib/LLVMgold.so: error loading plugin: /rustroot/bin/../lib/LLVMgold.so: cannot open sha
red object file: No such file or directory
```
while running `tikv-jemalloc-sys`'s `configure`, as well as some
```
Inherited flag "-fembed-bitcode=all" is not supported by the currently used CC
```
warnings

**Comment by workingjubilee** [comment]
@mrkajetanp

**Comment by clubby789** [comment]
Removing the inherited `-flto=thin` prevents the error
