### ISSUE TITLE
bug: Build::is_flag_supported `/std:c++17` returns false on 1.2.1 ->1.2.5 transition (on x86_64-pc-windows-msvc)

### ISSUE THREAD

**Issue by dj8yfo** [rust-lang/cc-rs#1324]
This is suppossedly a bug of https://docs.rs/cc/1.2.5/cc/struct.Build.html#method.is_flag_supported

on x86_64-pc-windows-msvc. 

After applying diff https://github.com/near/cargo-near/pull/281/commits/4a4a77263360b51fa6c46509ba2317582dd9a767
, running build script in https://github.com/brson/wasm-opt-rs/blob/8854bd8a58d7393c7bacd950884aea521ce8e19f/components/wasm-opt-sys/build.rs#L365 
fails https://github.com/near/cargo-near/actions/runs/12417889777/job/34669855813

![Image](https://github.com/user-attachments/assets/502d1c20-9353-4d45-91df-9fb5a83b1764)
![Image](https://github.com/user-attachments/assets/4adafbc0-227f-4dbd-9cc6-fa4a8e2d0fa7)

Pinning `cc` to 1.2.1 in https://github.com/near/cargo-near/pull/282 helps (build succeeds on the identical image)

**Comment by NobodyXu** [comment]
@dj8yfo I suspect it's because of https://github.com/rust-lang/cc-rs/commit/f770d563321c2a74bc8f0b34436242e0c111cd01

can you try forking cc and comment out that changes, and see if it fixes the problem for you?

**Comment by BD103** [comment]
Hi! We've also managed to reproduce this when running the build script for `wasm-opt-sys` v0.166.0 in https://github.com/TheBevyFlock/bevy_cli/pull/199. The exact error was caught by our CI [in this run](https://github.com/TheBevyFlock/bevy_cli/actions/runs/12537452515/job/34961554387) ([Archived version](https://github.com/user-attachments/files/18277656/6_Run.tests.windows-latest.txt)).

I don't have a Windows computer anymore, so I can't reproduce this locally, but let me know if there's anything else I can do to help!

**Comment by CryZe** [comment]
This reproduces with cc 1.2.5, not with 1.2.4.

**Comment by ChrisDenton** [comment]
I think this was caused by https://github.com/rust-lang/cc-rs/pull/1322 which removed the `-c` flag (i.e. don't invoke the linker).

It complains about msvcrt.lib not being found. Either we need to supply the lib path or else do something like:

```rust
cmd.args(["/link", "/entry:main"]);
```

To avoid depending on the C runtime libraries.

**Comment by ChrisDenton** [comment]
Oh wait, I just realised. `-c` on msvc has the opposite effect than `-c` on gnu compilers. https://learn.microsoft.com/en-us/cpp/build/reference/c-compile-without-linking?view=msvc-170

So we just need to be doing `-c` again, just gated on the msvc compiler. That is super confusing.
