### ISSUE TITLE
Library creation fails with Android NDK r23b

### ISSUE THREAD

**Issue by b-spencer** [rust-lang/cc-rs#636]
**Problem**

Using fresh installations of Rust installed on x86_64-unknown-linux-gnu (Debian 10) via the rustup method, compiling packages for Android with NDK r23b (the current LTS release) does not work.

**Steps**

1. `curl -sf -L https://static.rust-lang.org/rustup.sh | sh` (fresh install for the local user)

2. `rustup target add aarch64-linux-android`

3. Create an empty library crate that depends on `ring`:

```
cargo new --lib hello
echo 'ring = "0.16"' >>hello/Cargo.toml
```

4. Compile for the host and all is well:

```
$ cargo build
    Updating crates.io index
   Compiling libc v0.2.107
   Compiling cc v1.0.72
   Compiling once_cell v1.8.0
   Compiling spin v0.5.2
   Compiling untrusted v0.7.1
   Compiling ring v0.16.20
   Compiling hello v0.1.0 (/home/.../hello)
    Finished dev [unoptimized + debuginfo] target(s) in 7.48s
```

5. Compile for `aarch64-linux-android` the simple, documented way and it fails, but that's because of all the reasons in #459:

```
$ cargo build --target aarch64-linux-android
   Compiling untrusted v0.7.1
   Compiling spin v0.5.2
   Compiling once_cell v1.8.0
   Compiling libc v0.2.107
   Compiling ring v0.16.20
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/home/.../hello/target/debug/build/ring-b1c7634ecf998ee6/build-script-build` (exit status: 101)
...
```

6. Add all the workarounds from #459 and it still doesn't work:

```
$ PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/:$PATH \
  CC_aarch64_linux_android=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang \
  CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang \
  cargo build --lib --release --target aarch64-linux-android
   Compiling ring v0.16.20
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/home/.../hello/target/release/build/ring-14a8ac965b8995d8/build-script-build` (exit status: 1)
...
  --- stdout
  running: "aarch64-linux-android-ar" "cq" ...
  ...

  --- stderr

  error occurred: Failed to find tool. Is `aarch64-linux-android-ar` installed?
```

The newest versions of the Android NDK simply do not ship GNU binutils and thus there is no `aarch64-linux-android-ar` to use.  No amount of changing paths or environment variables is likely to make this work.  I suspect that the rust toolchain will need to use `llvm-ar` and the other LLVM tools instead if it is to work with the current LTS versions of the Android NDK.

**Comment by TroyNeubauer** [comment]
Same issue here. Would love to see a fix to allow me to use the current version of the NDK

**Comment by sidneywang** [comment]
Same issue here.

**Comment by sshxmz** [comment]
Same problem here.

outdated profile for cc::build:
default compiler = 'aarch64-linux-android21-clang'
default archiver = 'aarch64-linux-android-ar'

**Comment by rileyhawk1417** [comment]
> Same issue here. Would love to see a fix to allow me to use the current version of the NDK

Does version 22/21 have the files. Was hesitant after downloading via Androis tudio and manually downloading the NDK archive from the website.

**Comment by dot-asm** [comment]
Would you mind testing a variant of #657? "A variant" means that I would have to prepare a variant that would extend the suggested approach to android targets.

**Comment by dot-asm** [comment]
In the context I also wonder how do you specify the compiler? The background for the question is following. My understanding is that you're supposed to specify `linker` through .cargo/config.toml. In which case it would be only natural to use it even as default C compiler and use it to derive C++ compiler name...

**Comment by irediaes** [comment]
To fix copy and rename `llvm-ar` to `aarch64-linux-android-ar` in `${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/{SYSTEM}/bin`
 
Do this for all your target arch.

**Comment by dot-asm** [comment]
Isn't answer to all these questions `cargo install cargo-apk`?

> I don't understand why rust's tools' expectations don't align with how the Android NDK ships

It has nothing to do with Android. If you want to cross-compile for **any** platform, it is **your** responsibility to specify appropriate cross-linker. You can do it yourself or use helpers like `cargo-apk`. (Just in case, no, one can't do choose linker in a build script, it's too late.)

**Comment by briansmith** [comment]
Should this be closed? Everything in the description is so outdated that it is hard to see if it has any relevance today.

**Comment by NobodyXu** [comment]
Thanks, I've closed this.

If anyone still encounters this issue, feel free to open a new issue.
