### ISSUE TITLE
New Maintainers

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/cc-rs#663]
I'm reaching the end of my tenure of maintaining this crate. I can't keep up with the constant inundation of platforms into this crate and this has outgrown my own personal ability to manage. I feel nowadays like all I can do is rubber stamp big changes since I have no idea how the targets work, but at the same time it seems to be the case that code is just dumped in this crate and no one ever looks at it again until there's a bug. Personally, I can't keep up with that any more.

If someone would like to take over this crate please let me know. I realize though that this crate is very heavily depended on in the ecosystem, so I won't necessarily give this to the first person that shows up. I'll need to recognize you and you'll also need to understand the importance of this crate and its stability.

**Comment by sunface** [comment]
I have a idea, maybe you should create an organization like `cc-rs`, move the repo there ,and let other maintainers join in, each of them will account for certain targets.

This project is very great and important, ,if it is just moved to another github user, probably nothing will changed and things won't getting better.

**Comment by Dylan-DPC** [comment]
I can help with the organisation part. Have done so for a few crates already and being a rust team member, it might be easier

**Comment by Be-ing** [comment]
Thanks for recognizing your limits and asking for help @alexcrichton. :heart:

**Comment by spl** [comment]
I worked on `cc-rs` [a while back](https://github.com/alexcrichton/cc-rs/commits?author=spl). At the time, I did have some ideas for improving it, but I didn't get around to finishing them. I wouldn't mind giving a shot at maintenance, shared or otherwise.

**Comment by aloucks** [comment]
@m-ou-se I think it's a great idea to incorporate this crate into the `rust-lang` organization. If for whatever reason that doesn't happen, it might make sense to create a new org to host both this crate and [cmake-rs](https://github.com/alexcrichton/cmake-rs). It might also be worthwhile to host cmake-rs in the `rust-lang` org!

**Comment by dvc94ch** [comment]
any updates on this?

**Comment by m-ou-se** [comment]
We've discussed this in the Rust library team meeting this week, and we think it's best if `cc` and `cmake` are both moved to the `rust-lang` organisation. Currently, we won't have the bandwith to work on new features to these crates, but we will be able to review incoming PRs and make sure these crates stay maintained.

@alexcrichton If you're on board with this, can you transfer the repos to the `rust-lang` GitHub organisation, and invite `@rust-lang-owner` as owner to the crates on crates.io?

**Comment by alexcrichton** [comment]
Sounds good to me, thanks @m-ou-se and the other libs/rust-lang members!

I believe though I'll need to transfer these repositories to someone else first who has permission to create repositories within the rust-lang organization, currently if I try to perform the transfer I get the error:

>  You don’t have the permission to create public repositories on rust-lang 

Otherwise though I have invited the `rust-lang-owner` account to both `cc` and `cmake`

**Comment by alexcrichton** [comment]
Ok this repository is now moved over, thanks!

**Comment by Be-ing** [comment]
Unfortunately there haven't been any commits to master since July and pull requests are piling up without response...

**Comment by thomcc** [comment]
@Be-ing We're making a team for maintaining these crates: https://github.com/rust-lang/team/pull/861.
