### ISSUE TITLE
Should integrate cc-rs knowledge of linkers with rustc

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/cc-rs#693]
rustc currently has limited knowledge of the correct linker to use on various platforms. cc-rs has a much better idea of which linker to use. There's been a long-standing goal that many people have advocated of making the compiler use cc-rs to find the linker; this would fix cross-compilation for many targets.

Filing this issue to track that possibility. There are also corresponding issues on the rustc repo, which this should link to / be linked from.

**Comment by dot-asm** [comment]
> there already is a dependency, on Windows

For reference. The dependency on Windows is of different nature. cc-rs helps rustc to find the toolchain components it's looking for, but doesn't tell which components to use.
