### ISSUE TITLE
Empty module causes an error

### ISSUE THREAD

**Issue by Booplicate** [rust-lang/cc-rs#714]
Hello, I'm not entirely sure if the problem is in `cc-rs` itself, but the traceback led me here.

I'm using a few crates,  `cc-rs` is one of their dependencies. When I'm trying to use `cargo build --release`, I'm getting the following error:
```
error[E0425]: cannot find function `find` in module `windows_registry`
    --> C:\Users\User\.cargo\registry\src\github.com-[xxx]\cc-1.0.73\src\lib.rs:1903:41
     |
1903 |         let mut cmd = windows_registry::find(&target, tool).unwrap_or_else(|| self.cmd(tool));
     |                                         ^^^^ not found in `windows_registry`

error[E0425]: cannot find function `find_tool` in module `windows_registry`
    --> C:\Users\User\.cargo\registry\src\github.com-[xxx]\cc-1.0.73\src\lib.rs:2180:40
     |
2180 |         let cl_exe = windows_registry::find_tool(&target, "cl.exe");
     |                                        ^^^^^^^^^ not found in `windows_registry`

error[E0425]: cannot find function `find` in module `windows_registry`
    --> C:\Users\User\.cargo\registry\src\github.com-[xxx]\cc-1.0.73\src\lib.rs:2514:37
     |
2514 |             match windows_registry::find(&target, "lib.exe") {
     |                                     ^^^^ not found in `windows_registry`
```
At first I was confused, but then I checked `windows_registry.rs` and it was empty. I tried clearing cache, rebuilding, using the latest versions of the crates, nothing fixed the problem.

Could you assist me fixing this or guide me in a proper direction? Or is it an actual issue with this crate/cargo/some other crate? Let me know if you need more information.

**Comment by ChrisDenton** [comment]
What you're saying indicates that the cargo downloaded files are somehow corrupted, so deleting `C:\Users\User\.cargo\registry` should fix it by forcing it to be re-downloaded. If it doesn't then I'm not sure what else to suggest. You might get more help on Rust's support forums, chat or cargo issue tracker. I don't think this an issue with cc itself.

**Comment by Booplicate** [comment]
You're right, it was an issue with cargo, I tried the same in a fresh environment and it worked, sorry for the hassle!
