### ISSUE TITLE
cc `1.0.74` no longer compiles under Nix

### ISSUE THREAD

**Issue by arxanas** [rust-lang/cc-rs#745]
Hi, I'm not really a Nix user so I don't know if this is a problem with `cc` or Nix, but I thought I'd report it here anyways. The version 1.0.74 causes this failure under Nix:

```
git-branchless>   running: "ar" "s" "/build/source/target/x86_64-unknown-linux-gnu/debug/build/libz-sys-7e8bf8c1b3fed440/out/lib/libz.a"
git-branchless>   exit status: 0
git-branchless>   cargo:rustc-link-lib=static=z
git-branchless>   cargo:rustc-link-search=native=/build/source/target/x86_64-unknown-linux-gnu/debug/build/libz-sys-7e8bf8c1b3fed440/out/lib
git-branchless>   --- stderr
git-branchless>   src/smoke.c:1:10: fatal error: zlib.h: No such file or directory
git-branchless>       1 | #include <zlib.h>
git-branchless>         |          ^~~~~~~~
git-branchless>   compilation terminated.
git-branchless>   thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', /build/cargo-vendor-dir/libz-sys-1.1.8/build.rs:138:61
```

You can see an example of the full output here: https://github.com/arxanas/git-branchless/actions/runs/3412839520/jobs/5678849762

If this is a problem with Nix, then feel free to close.

**Comment by thomcc** [comment]
Nothing in https://github.com/rust-lang/cc-rs/releases/tag/1.0.74 (or the [commits from 1.0.73 to 1.0.74](https://github.com/rust-lang/cc-rs/compare/1.0.73...1.0.74)) stand out to me as impacting header path. It also might be `libz-sys` issue?

I'm also not a Nix user, but I know @Hoverbear does Nix and Rust stuff, and might be able to indicate if this seems like an issue with Nix or cc-rs.

**Comment by thomcc** [comment]
Hmm, please reopen if there's something we can do to help here, but it seems like an issue with your repository's Nix configuration and not with the recent release. Thanks a ton @Hoverbear.
