### ISSUE TITLE
Please yank the most-broken versions of the dead gcc crate

### ISSUE THREAD

**Issue by kornelski** [rust-lang/cc-rs#749]
I'm trying to [get the ecosystem working with `--minimal-versions` flag](https://github.com/rust-lang/cargo/issues/5657#issuecomment-1308974836), and super-old versions of `gcc` are among problematic crates.

It would be helpful if you yanked all versions older than 0.3.23, which pull in the dead `advapi32-sys` crate and some aren't even compatible with Rust 1. These versions are over 6 years old and their download numbers are below bot-activity noise floor.

```bash
cargo new gcc;
cd gcc;
for v in "0.0.1" "0.0.2" "0.1.0" "0.1.1" "0.1.2" "0.1.3" "0.1.4" "0.1.5" "0.1.6" "0.1.7" "0.2.0" "0.2.1" "0.3.0" "0.3.1" "0.3.10" "0.3.11" "0.3.12" "0.3.13" "0.3.14" "0.3.15" "0.3.16" "0.3.17" "0.3.18" "0.3.19" "0.3.2" "0.3.20" "0.3.21" "0.3.22" "0.3.4" "0.3.5" "0.3.6" "0.3.8" "0.3.9"; do
    cargo yank --vers "$v";
done
```

**Comment by madsmtm** [comment]
@alexcrichton who has ownership over this crate

**Comment by NobodyXu** [comment]
Thank you alexcrichton
