### ISSUE TITLE
`cc` passes `-Fo` flag to `gcc` on windows, which is ignored

### ISSUE THREAD

**Issue by divagant-martian** [rust-lang/cc-rs#800]
This should be `-o` similar to previous issue #482

**Comment by Spencer1O1** [comment]
I submitted a pull request that resolves this issue [#820](https://github.com/rust-lang/cc-rs/pull/820)
Just waiting to get it merged

**Comment by Spencer1O1** [comment]
@thomcc merged the request so this issue should be closed now.
