### ISSUE TITLE
1.0.80 complie error zstd-sys v2.0.8+zstd.1.5.5

### ISSUE THREAD

**Issue by cowbear6598** [rust-lang/cc-rs#841]
I open a new project and use actix-web v4.3.1 in dependencies, and Cargo.lock set 1.0.80 version cause my project build fail, this is Cargo.lock's content

[[package]]
name = "cc"
version = "1.0.80"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "51f1226cd9da55587234753d1245dd5b132343ea240f26b6a9003d68706141ba"
dependencies = [
 "jobserver",
 "libc",
]

and my another project is build successfully but it use 1.0.79, this is content

[[package]]
name = "cc"
version = "1.0.79"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "50d30906286121d95be3d479533b458f87493b30a4b5f79a607db8f5d11aa91f"
dependencies = [
 "jobserver",
]

attach file is error message and my build toolchain, I use Clion 2023.2 + MinGW

[error.txt](https://github.com/rust-lang/cc-rs/files/12236235/error.txt)
![1690953461234](https://github.com/rust-lang/cc-rs/assets/39182219/2944ebf0-c9b2-41ff-b47d-7260789b620c)

**Comment by NobodyXu** [comment]
error message:

```
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: InvalidData, message: "stream did not contain valid UTF-8" }', C:\Users\cowbe\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cc-1.0.80\src\lib.rs:3837:47
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library\std\src\panicking.rs:593
     1: core::panicking::panic_fmt
               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library\core\src\panicking.rs:67
     2: core::result::unwrap_failed
               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library\core\src\result.rs:1651
     3: core::result::Result<T,E>::unwrap
     4: cc::PrintThread::new::{{closure}}
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by NobodyXu** [comment]
I will submit a fix for this.

**Comment by NobodyXu** [comment]
@cowbear6598 I've opened #842 for this, can you please have a try to see if it fixed the problem for you?

**Comment by Originalimoc** [comment]
thanks for the 1.0.79 checksum haha😅(add: anyway to get whatever version checksum?)

**Comment by cowbear6598** [comment]
@NobodyXu 1.0.81 fixed, new project and my old project are working good.

**Comment by bazhenov** [comment]
Seems like very similar problem is still affecting opencv build: https://github.com/twistedfall/opencv-rust/issues/480. 1.0.79 working, 80, 81 doesn't.
