### ISSUE TITLE
Issues with releasing and reacquiring implicit jobserver token

### ISSUE THREAD

**Issue by tgnottingham** [rust-lang/cc-rs#858]
I was trying to optimize build times and found that -sys crate dependencies seemed to be taking a long time according to the `cargo build --timings` output. Further investigation showed that these dependencies didn't take as long to build in isolation (with concurrency controlled for with `-j1`), which seemed odd.

More investigation led to https://github.com/rust-lang/cargo/issues/7689 and https://github.com/rust-lang/cargo/pull/7344 being the culprits.

Long story short, I think that releasing and reacquiring the implicit jobserver token causes the `cargo build --timings` output to be misleading.

Take this example:

```
cargo new example
cd example
cargo add bzip2-sys nng-sys zstd-sys 
cargo build -j1 --timings
```

And the resulting graph:

![Screenshot from 2023-08-19 15-58-31](https://github.com/rust-lang/cc-rs/assets/3668166/61724214-bccc-4e77-ac4c-8a3b263e2453)

If I build each of the -sys dependencies in isolation, bzip2-sys takes ~0.5s, nng-sys takes ~14s, and zstd-sys takes ~15s. Note the inconsistency with the graph.

What appears to be happening, roughly, in this case is:

1. bzip2-sys build script starts
1. cc for bzip2-sys releases its implicit token before its processing loop
1. That allows zstd-sys build script to start
1. cc for zstd-sys releases its implicit token before its processing loop
1. That allows nng-sys build script to start
1. nng-sys build script runs to completion in ~14s
1. nng-sys starts and runs to completion
1. zstd-sys build script resumes and runs for ~2.5s
1. cc for zstd-sys releases a token
1. That allows bzip2-sys build script to resume and run to completion in ~0.5s
1. bzip2-sys starts and runs to completion
1. zstd-sys build script resumes and runs to completion in ~12.5s
1. zstd-sys starts and runs to completion

If you assume this is more or less what happened, the bars in the graph make sense and the timings are consistent with how long the -sys crates take to build in isolation.

Also, I don't know how cargo schedules dependency building, but I'm wondering if this issue could cause increases in compile times by delaying builds of dependents in an unexpected way. If cargo specifically chooses to compile one dependency earlier to unlock its ability to start compiling dependents, presumably with the goal of reducing overall build time, then I think this choice might be undermined by the behavior seen here, since we see other crates sort of cut in line.

I'm also wondering if, once this is fixed, the change introduced by https://github.com/rust-lang/cargo/pull/7344 should be reverted or modified somehow, or if doing so would cause problems with older versions of cc on older versions of cargo.

**Comment by NobodyXu** [comment]
Yeah that is a really unfortunate situation.
I tried to remove this in #779 but failed.

NOTE that if any `build.rs` spawns multiple threads to compile in parallel, they would release even more tokens and then acquire.

I'm really not sure how to fix this.
Perhaps the solution is to not re-acquire the token at all, or add a new method `jobserver::Client::try_acquire`.
