### ISSUE TITLE
`is_flag_supported` returns false negative

### ISSUE THREAD

**Issue by tcharding** [rust-lang/cc-rs#892]
When building with the `wasm32-unknown-unknown` target flags are not getting passed correctly to `clang`.

`cc::Builder::new().flag_if_supported("-Wno-unused-function")` ignores the flag but `flag("-Wno-unused-function")` works.

It looks like `is_flag_supported` is giving a false negative. I managed to get this error

```
warning: output: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "clang: error: unable to execute command: Executable \"wasm-ld-14\" doesn't exist!\nclang: error: linker command failed with exit code 1 (use -v to see invocation)\n" }
```

My machine does not have `wasm-ld-14` installed, it has `wasm-ld-15`. I was not able to work out why the wrong version is used in `is_flag_supported` but the correct version is used when running `try_compile`.

**Comment by dot-asm** [comment]
Community solution was suggested in #839.

**Comment by thomcc** [comment]
That one had slipped under my radar (Had been pretty busy with $DAYJOB around the time it was submitted). I've merged it, and it should be in the next release.

**Comment by tcharding** [comment]
Awesome, thanks!
