### ISSUE TITLE
Cut 1.0.84 Release

### ISSUE THREAD

**Issue by Augustyniak** [rust-lang/cc-rs#893]
Cutting 1.0.84 would help us to solve issues with compiling on target iOS platforms.

We recently run into an issue with https://github.com/rust-lang/libz-sys crate where it would not be able to correctly compile a simple `.c` file on target iOS platform due to bitcode being enabled for all of iOS / watch OS builds. 

Bitcode was disabled as part of https://github.com/rust-lang/cc-rs/pull/812 but it's not included in 1.0.83 version of `cc` crate.

**Comment by dot-asm** [comment]
I'd like to use the opportunity to plug #866 prior release. I mean it fixes an actual problem...

**Comment by thomcc** [comment]
I'll try and cut a release this weekend. There are some reviews I'll try to get to before then. I'll take a look at #866 too.

**Comment by thomcc** [comment]
It will probably be a little later than this weekend, I'd like for us to get the jobserver changes in #889 done, and they need a bit longer.

**Comment by thomcc** [comment]
https://github.com/rust-lang/cc-rs/releases/tag/1.0.84
