### ISSUE TITLE
[Feature Request] Add support for zig

### ISSUE THREAD

**Issue by cathaysia** [rust-lang/cc-rs#897]
zig supports an easy-to-use cross-compilation experience, and also supports c and cpp. However, cc-rs' support for zig needs to be improved (mainly to perform some special processing when zig is recognized).

If cc-rs can accept these changes, I can make these work.
```[tasklist]
### Tasks
- [ ] support `cc.compiler("zig cc")`
- [ ] disable sccache when using zig cc
```

**Comment by NobodyXu** [comment]
> disable sccache when using zig cc

Does zig-cc not work with sccache?
Is this something that can be fixed in zig itself?

**Comment by cathaysia** [comment]
the problem is sccache does not support zig, zig has it's own cache system.
________________________________

**Comment by NobodyXu** [comment]
> the problem is sccache does not support zig,

That's unfortunate...

> zig has it's own cache system.

Can you provide me a link to the doc please?

I've been using cargo-zigbuild for a while but I never look deep into it, didn't know it has a caching system.

**Comment by cathaysia** [comment]
maybe this?

https://ziglang.org/documentation/master/#C-Translation-Caching

and here are some links:

- https://gist.github.com/matu3ba/92e5df1166c51b3725dbd04f7ff1cb4e
- https://github.com/ziglang/zig/issues/2599

**Comment by NobodyXu** [comment]
Thanks, but https://gist.github.com/matu3ba/92e5df1166c51b3725dbd04f7ff1cb4e is outdated (its content says it's outdated).

For https://ziglang.org/documentation/master/#C-Translation-Caching , it just says it uses zig caching system but there's no doc for the zig caching system.

**Comment by cathaysia** [comment]
Yeah, but I guess we don't need to look into zig's caching system? We just need to know that it does.

**Comment by NobodyXu** [comment]
> Yeah, but I guess we don't need to look into zig's caching system? We just need to know that it does.

Yeah I'm just interested in how it works, I do think it's a good idea to support zig-cc, I would probably open a PR after #893

**Comment by cathaysia** [comment]
I can't find the author's specific description of the zig cache system. Here it may be useful to you:

- https://ziglang.org/download/0.4.0/release-notes.html#Build-Artifact-Caching
- https://apenwarr.ca/log/20181113

Of course, the best thing is probably to read the source code:

- https://github.com/ziglang/zig/blob/bddbbef32b4a42237ca84352a26a93bf250da918/src/cache_hash.hpp
- https://github.com/ziglang/zig/blob/master/lib/std/Build/Cache.zig

**Comment by NobodyXu** [comment]
Thanks!

I also found the cache dir using `zig env` and checks its content, now I have a rough idea on how it works.

**Comment by thomcc** [comment]
The problem with supporting zig is that they don't use a standard names for the different target triples, and have indicated they'll likely change how this works in a future version. We'd need mappings for this and it would be a big pain.

In the mean time [`cargo-zigbuild`](https://github.com/rust-cross/cargo-zigbuild) sets everything right to use `cc` with zig, I'd recommend that.

**Comment by cathaysia** [comment]
emm, let me explain why I don't want rust-zigbuild.

This question originally arose because I wanted to compile some c source code into a static library in rust, the cargo-zigbuild was descripted "Compile Cargo project with zig as linker", but I don't need using it as a linker. 

so I use cc-rs, and pass zig's triple to $CC, it works fine. I open this issue in the hope that cc can solve some common problems (for example, a compiler like zig cc can only be passed through $CC, but not through the compiler function).

Of course, I now know why my cross-compiling with clang failed (because the nix-shell I used replaced the default clang, and the clang they provided added some OS-specific parameters, and just needed to change the compiler to the system The default will do)

**Comment by NobodyXu** [comment]
P.S. `cargo-zigbuild cc` can be used as a wrapper, though I do think cc should support zig-cc

**Comment by cathaysia** [comment]
ok, so let's close this issue

**Comment by NobodyXu** [comment]
cc @cathaysia I now think rustup should ship zig-cc for cc-rs to use and use it for linking

https://internals.rust-lang.org/t/bundle-zig-cc-in-rustup-by-default/22096
