### ISSUE TITLE
New 1.0.84 causes compilation errors in Ring

### ISSUE THREAD

**Issue by calavera** [rust-lang/cc-rs#899]
It looks like the new 1.0.84 introduced some breaking changes. I'm not familiar with the internals of cc-rs, or the changes that came in this release, but people starting having issues compiling Ring as soon as this release was cut:

https://github.com/cargo-lambda/cargo-lambda/issues/566
https://github.com/rust-cross/cargo-zigbuild/issues/198

Here someone mentions that going back to 1.0.83 fixes the problem: https://github.com/cargo-lambda/cargo-lambda/issues/566#issuecomment-1807274805

I'm guessing this was not intentional, but given the amount of changes I don't know how to proceed. I'll appreciate some guidance on how to solve the problem. Should that release be rolled back? What's the project's versioning strategy?

**Comment by NobodyXu** [comment]
Is this a dup of #198

**Comment by NobodyXu** [comment]
Sorry I thought there was another cc issue on this, but turns out it's in cargo-zigbuild repository.

**Comment by NobodyXu** [comment]
cargo-zigbuild has merged in https://github.com/rust-cross/cargo-zigbuild/pull/199 and cut a new release to fix this.

I will close this as completed since it is already fixed in cargo-zigbuild.
