### ISSUE TITLE
Allow suppression of cargo warning instructions in output

### ISSUE THREAD

**Issue by scootermon** [rust-lang/cc-rs#916]
Right now cc allows for the suppression of specific cargo instructions using `.cargo_metdata(false)`, but this doesn't affect the output of `cargo:warning=` lines.
I'm working on a bindings library which uses compilation tests to determine whether certain features are supported or not. CC already almost fully supports this use-case[^1], the only issue being that the warnings and errors show up as though they're part of the "main compilation".

Since I belive this feature is unrelated to the behaviour of `cargo_metadata`, how would you feel about adding a `.cargo_warnings(false)` setting that allows us to disable the warnings?
I'm of course happy to contribute the implementation.

[^1]: Shoutout to #912, which will also help here because it helps remove an otherwise unnecessary step from the compilation tests

**Comment by NobodyXu** [comment]
Yes I'm willing to review a PR disabling the warnings.
