### ISSUE TITLE
`cc` 1.0.86 seems to erroneously enable parallelism by default on certain platforms

### ISSUE THREAD

**Issue by IGI-111** [rust-lang/cc-rs#964]
Compiling `openssl-sys` on `aarch64-unknown-linux-gnu`, which uses `cc` fails with the following error:

```
 --- stderr
  make: *** read jobs pipe: Resource temporarily unavailable.  Stop.
  make: *** Waiting for unfinished jobs....
  thread 'main' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-src-300.2.3+3.2.1/src/lib.rs:611:9:



  Error building OpenSSL:
      Command: cd "/target/aarch64-unknown-linux-gnu/release/build/openssl-sys-6a5ed052a12e98be/out/openssl-build/build/src" && MAKEFLAGS="-j --jobserver-fds=7,8 --jobserver-auth=7,8" "make" "build_libs"
      Exit status: exit status: 2
```

This is a known issue with building openssl on this platform using parallelism:
https://github.com/rust-lang/cargo/issues/13476
https://github.com/sfackler/rust-openssl/issues/2179

However, the `parallel` feature is [not enabled](https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/Cargo.toml) by `openssl-sys` and compiling with the exact same version of `openssl-sys` but using `cc` 1.0.83 succeeds, which leads me to believe there is a breaking change or bug in the 1.0.86 version.

**Comment by NobodyXu** [comment]
Duplicate of #962 , there's probably another crate that enables feature cc/parallel

To solve this problem once and for all, I believe we need to change rust-lang/jobserver.

A temporary fix can be done here for openssl-sys, by disabling `O_NONBLOCK` when the jobserver is not used, though it is racy and if you spawn `make` on another thread it could still fail, but it will work for openssl if its `build.rs` is single-thread only.

**Comment by IGI-111** [comment]
Indeed after some investigation I think I found another crate that enables it in my own build, since building `openssl-sys` on its own does not fail.

In this case it was `libgit2-sys`, which does so even when configured to vendor openssl.

Since this doesn't seem to be a `cc` issue, I'll close this.

Good luck trying to fix this permanently and thanks for the pointers.
