### ISSUE TITLE
cc 1.0.87 produces tons of warnings on `cargo check` 

### ISSUE THREAD

**Issue by ahlinc** [rust-lang/cc-rs#970]
After update to the latest `cc 1.0.87` I see tons of warnings for every dependency crate that uses `cc` in its `build.rs`.
Warnings looks like:
```
warning: some-dependency-crate@0.0.1: running: "cc" "--version"
warning: some-dependency-crate@0.0.1: exit status: 0
warning: some-dependency-crate@0.0.1: running: "cc" "--version"
warning: some-dependency-crate@0.0.1: exit status: 0
warning: some-dependency-crate@0.0.1: running: "cc" "--version"
warning: some-dependency-crate@0.0.1: exit status: 0
warning: some-dependency-crate@0.0.1: running: "cc" "--version"
warning: some-dependency-crate@0.0.1: exit status: 0
warning: some-dependency-crate@0.0.1: running: "ar" "s" "/home/user/some-code/target/debug/build/some-dependency-crate-b229f6f8a8f92087/out/libfoo.a"
warning: some-dependency-crate@0.0.1: exit status: 0
```
It seems like that some debug logging was overlooked and now the `cc` crate reports all sub command exit statuses as cargo warnings.

**Comment by NobodyXu** [comment]
It's #960 where I suggest to turn them into warnings, I think we need to add a new debugging printing that is enabled by default (but without `cargo:warning=` prefix so it's not shown by default), that can be disabled.

**Comment by NobodyXu** [comment]
cc @amaanq
